# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fc405dcbc4b0b872ae71e4ec699f4f24d088a167f962b54b118645a9ffe2c47a23c2c542fcd5b516f88132fed1c0bd0590c310e1e821256bb13924800c5343f

test:
  secret_key_base: 80ab5dead44f6c61b71c00ea5b23ec9b857ff6e10dbd813426ce4809c849942ad0fef152b52a3777a4b28336db1536fdd08945d4273ee0dcd7d33fdf11ce58ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
